# ======================================
# 联邦学习框架核心配置
# ======================================
federated:
  rounds: 100 # 联邦学习总轮数
  num_nodes: 10 # 联邦节点总数
  aggregation: fedavg # 聚合算法 (fedavg, fedprox, etc.)
  node_selection_ratio: 0.3 # 每轮选择的节点比例
  evaluation_interval: 5 # 每多少轮评估一次全局模型
  save_model_interval: 10 # 每多少轮保存一次全局模型
  max_communication_delay: 60 # 最大通信延迟(秒)

# ======================================
# 模型架构配置
# ======================================
model:
  global:
    name: FeatureExtractor # 全局模型名称
    type: resnet18 # 模型类型
    input_dim: 32 # 输入维度 (e.g., 32 for CIFAR)
    output_dim: 10 # 输出维度 (分类数)
    hidden_dims: [64, 128] # 隐藏层维度
    dropout: 0.2 # Dropout概率

  core_net: # 认知网络配置 (P2)
    name: CoreNet
    input_dim: 256 # 输入特征维度
    hidden_dims: [128, 64] # 隐藏层维度
    output_dim: 3 # 输出维度 (ID, Near-OOD, Far-OOD)
    temperature: 1.0 # Softmax温度参数

# ======================================
# 训练参数配置
# ======================================
training:
  batch_size: 32 # 训练批大小
  learning_rate: 0.01 # 基础学习率
  optimizer: sgd # 优化器 (sgd, adam)
  momentum: 0.9 # SGD动量
  weight_decay: 1e-4 # 权重衰减
  epochs: 5 # 本地训练轮数
  online_epochs: 1 # 在线学习轮数 (P3)
  online_lr: 0.001 # 在线学习率 (P3)

# ======================================
# 数据配置
# ======================================
data:
  dataset: cifar10 # 数据集名称 (cifar10, mnist, femnist)
  root_dir: ./data # 数据集根目录
  test_ratio: 0.2 # 测试集比例
  ood_ratio: 0.3 # 本地数据中OOD样本的比例
  iid_distribution: false # 数据是否IID分布
  num_classes: 10 # 类别数

  # 数据增强配置
  augmentation:
    enabled: true
    resize: [32, 32]
    random_crop: true
    random_hflip: true
    normalize: true
    mean: [0.4914, 0.4822, 0.4465] # CIFAR10均值
    std: [0.2470, 0.2435, 0.2616] # CIFAR10标准差

  # 认知缓存模块配置 (P2)
  cognitive_cache:
    id_threshold: 0.8 # ID数据置信度阈值
    near_ood_threshold: 0.5 # Near-OOD阈值
    far_ood_threshold: 0.2 # Far-OOD阈值
    buffer_size: 1000 # 数据缓冲池大小

# ======================================
# 评估与日志配置
# ======================================
evaluation:
  metrics: [accuracy, f1_score] # 评估指标
  ood_detection_metrics: [auroc, fpr95] # OOD检测指标
  log_interval: 10 # 日志记录间隔
  save_results: true # 是否保存评估结果
  results_dir: ./results # 结果保存目录

logging:
  level: INFO # 日志级别 (DEBUG, INFO, WARNING, ERROR)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: ./logs/fed_learning.log # 日志文件路径
  console: true # 是否输出到控制台

# ======================================
# 硬件与性能配置
# ======================================
hardware:
  device: cuda # 训练设备 (cpu, cuda)
  num_workers: 4 # 数据加载工作线程数
  pin_memory: true # 是否固定内存
  fp16: false # 是否使用混合精度训练
  gpu_ids: [0] # 使用的GPU ID列表

# ======================================
# 实验特定配置
# ======================================
experiment:
  name: baseline_fed_learning # 实验名称
  description: "Baseline federated learning with OOD detection"
  tags: [baseline, cifar10] # 实验标签
  seed: 42 # 随机种子
  resume: false # 是否从检查点恢复
  checkpoint_dir: ./checkpoints # 检查点保存目录
